version: '3'
services:
  backend:
    build: ./celestixai-backend
    ports:
      - "8000:8000"
    depends_on:
      - database
    environment:
      DATABASE_URL: "postgresql://postgres:root@database:5432/celestixai-backend"
    volumes:
      - backenddata:/app
      - ./celestixai-backend:/app
    networks:
      - backend_network

  frontend:
    build: ./celestixai-frontend
    ports:
      - "3000:3000"
    networks:
      - backend_network

  database:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: celestixai-backend
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend_network

  ollama:
    image: ollama/ollama:0.1.29
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    networks:
      - backend_network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    ports:
      - 6333:6333
      - 6334:6334
    expose:
      - 6333
      - 6334
      - 6335
    # configs:
    #   - source: qdrant_config
    #     target: /qdrant/config/production.yaml
    volumes:
      - ./qdrant_data:/qdrant_data
    networks:
      - backend_network

networks:
  backend_network:

volumes:
  pgdata:
  backenddata:
  ollama:
  qdrant_data:
