version: '3'
services:
  backend:
    build: ./celestixai-backend
    ports:
      - "8000:8000"
    depends_on:
      - database
    environment:
      DATABASE_URL: "postgresql://postgres:root@database:5432/celestixai-backend"
      PYTHONDONTWRITEBYTECODE: 1
      PYTHONUNBUFFERED: 1
    volumes:
      - ./celestixai-backend:/app  # Mount the entire backend directory
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload  # Override CMD to enable auto-reload
    networks:
      - backend_network

  frontend:
    build:
      context: ./celestixai-frontend
      dockerfile: Dockerfile.dev  # Specify the development Dockerfile
    ports:
      - "3000:5173"
    volumes:
      - ./celestixai-frontend:/app  # Mount the entire frontend directory
      - /app/node_modules  # Anonymous volume to preserve node_modules
    command: npm run dev # Override CMD to run in dev mode
    networks:
      - backend_network

  database:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: celestixai-backend
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend_network

  ollama:
    image: ollama/ollama:0.4.0-rc8
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    networks:
      - backend_network

  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    ports:
      - 6333:6333
      - 6334:6334
    volumes:
      - ./qdrant_data:/qdrant_data
    networks:
      - backend_network

networks:
  backend_network:

volumes:
  pgdata:
  ollama:
  qdrant_data:
