"""Add created_at and updated_at columns

Revision ID: 57b99e277ae4
Revises: 
Create Date: 2024-02-05 09:27:46.312095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '57b99e277ae4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_model_id', table_name='model')
    op.drop_index('ix_model_model_name', table_name='model')
    op.drop_index('ix_model_parameters', table_name='model')
    op.drop_table('model')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_firstname', table_name='users')
    op.drop_index('ix_users_id', table_name='users')
    op.drop_index('ix_users_lastname', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_dataset_filename', table_name='dataset')
    op.drop_index('ix_dataset_id', table_name='dataset')
    op.drop_index('ix_dataset_uuid', table_name='dataset')
    op.drop_table('dataset')
    op.drop_index('ix_model_constellation_filename', table_name='model_constellation')
    op.drop_index('ix_model_constellation_icon_filename', table_name='model_constellation')
    op.drop_index('ix_model_constellation_icon_uuid', table_name='model_constellation')
    op.drop_index('ix_model_constellation_id', table_name='model_constellation')
    op.drop_index('ix_model_constellation_model_name', table_name='model_constellation')
    op.drop_index('ix_model_constellation_parameters', table_name='model_constellation')
    op.drop_index('ix_model_constellation_uuid', table_name='model_constellation')
    op.drop_table('model_constellation')
    op.drop_index('ix_models_id', table_name='models')
    op.drop_index('ix_models_model_name', table_name='models')
    op.drop_index('ix_models_parameters', table_name='models')
    op.drop_table('models')
    op.drop_index('ix_chats_id', table_name='chats')
    op.drop_table('chats')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chats',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('chat', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='chats_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='chats_pkey')
    )
    op.create_index('ix_chats_id', 'chats', ['id'], unique=False)
    op.create_table('models',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('filename', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('model_constellation_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fine_tuned_model_path', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('fine_tuned', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('train', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('model_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('parameters', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['model_constellation_id'], ['model_constellation.id'], name='models_model_constellation_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='models_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='models_pkey'),
    sa.UniqueConstraint('uuid', name='models_uuid_key')
    )
    op.create_index('ix_models_parameters', 'models', ['parameters'], unique=False)
    op.create_index('ix_models_model_name', 'models', ['model_name'], unique=False)
    op.create_index('ix_models_id', 'models', ['id'], unique=False)
    op.create_table('model_constellation',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('model_constellation_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('icon_uuid', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('icon_filename', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('filename', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('model_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('parameters', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('model_class', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('model_task', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('file_size', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='model_constellation_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_model_constellation_uuid', 'model_constellation', ['uuid'], unique=True)
    op.create_index('ix_model_constellation_parameters', 'model_constellation', ['parameters'], unique=False)
    op.create_index('ix_model_constellation_model_name', 'model_constellation', ['model_name'], unique=False)
    op.create_index('ix_model_constellation_id', 'model_constellation', ['id'], unique=False)
    op.create_index('ix_model_constellation_icon_uuid', 'model_constellation', ['icon_uuid'], unique=False)
    op.create_index('ix_model_constellation_icon_filename', 'model_constellation', ['icon_filename'], unique=False)
    op.create_index('ix_model_constellation_filename', 'model_constellation', ['filename'], unique=False)
    op.create_table('dataset',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('uuid', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('filename', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('file_size', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name='dataset_owner_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='dataset_pkey')
    )
    op.create_index('ix_dataset_uuid', 'dataset', ['uuid'], unique=True)
    op.create_index('ix_dataset_id', 'dataset', ['id'], unique=False)
    op.create_index('ix_dataset_filename', 'dataset', ['filename'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('firstname', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('lastname', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='users_pkey')
    )
    op.create_index('ix_users_lastname', 'users', ['lastname'], unique=False)
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.create_index('ix_users_firstname', 'users', ['firstname'], unique=False)
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    op.create_table('model',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('filename', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('model_constellation_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fine_tuned_model_path', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('fine_tuned', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('train', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('model_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('parameters', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['model_constellation_id'], ['model_constellation.id'], name='model_model_constellation_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='model_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='model_pkey'),
    sa.UniqueConstraint('uuid', name='model_uuid_key')
    )
    op.create_index('ix_model_parameters', 'model', ['parameters'], unique=False)
    op.create_index('ix_model_model_name', 'model', ['model_name'], unique=False)
    op.create_index('ix_model_id', 'model', ['id'], unique=False)
    # ### end Alembic commands ###
